export const MandatoryFields = {
  eblast: ['EmailAddress', 'NameFirst', 'NameLast'],
  event_info: [
    'eventName',
    'EventInfoTxt',
    'StartDate',
    'StartTime',
    'EndDate',
    'EndTime',
    'ShowSecurityType',
    'eventCategory',
    // 'GoogleMerchantId',
    'venueCity',
    'venuePostalCode',
    'mainPhoneNumber',
    'eventType',
    'eventFormat',
    'venueAddress',
    'ReqdQualIdFlag',
    'ReqdQualPayFlag',
    'ReqdQualLicFlag',
    'ReqdPhotoFlag',
    'EventShowYear',
    // 'GatewayName',
    // 'GatewayMerchantId',
    'ReqdNoqualFlag',
  ],
  event_costs: [
    'EventRegType',
    'RegcodeEvtcode',
    // 'OnsiteStartDate',
    // 'OnsiteEndDate',
    // 'OnsiteRate',
  ],
  qualifications: ['regType', 'qualification'],
  sessions: [
    'StartDate(MM/DD/YYYY)',
    'StartTime(24H)',
    'EndDate(MM/DD/YYYY)',
    'EndTime(24H)',
    'PublicPrivate',
    'SessionDescription',
    'sessionType',
    'AllotmentRoomCapacity',
    'Topic',
    'SpeakerName',
    'SpeakerBio',
    'SessionRate',
  ],
  questions_goals: ['PollingType', 'FocusType', 'Description'],
  discounts: ['DiscountCode', 'Description', 'Discount'],
  page_customizations: ['Workflow', 'PageList'],
  membershipAllotment: [
    'Member_ID',
    'First_Name',
    'Last_Name',
    'Company_Name',
    'Addr1',
    'City',
    'State_Code',
    'Postal_Code',
  ],
  exhibitorAllotment: [
    'Exhibitor_ID',
    'Primary_Contact_Last_Name',
    'Address1',
    'City',
    'State',
    'Postal_Code',
    'Primary_Contact_Email_Address',
    'Phone_Number',
  ],
};

export const QuestionResponseUniqProps = [
  'demQuestion',
  'Description',
  'FocusType',
  'PollingType',
  'ResponseFieldType',
  'dedValue',
  'dedDescription',
  'additionalInfoName',
  'additionalInfoValue',
];
