export const countryCodes = [
    { "code": "AD", "name": "The Principality of Andorra" },
    { "code": "AE", "name": "The United Arab Emirates" },
    { "code": "AF", "name": "The Islamic Republic of Afghanistan" },
    { "code": "AG", "name": "Antigua and Barbuda" },
    { "code": "AI", "name": "Anguilla" },
    { "code": "AL", "name": "The Republic of Albania" },
    { "code": "AM", "name": "The Republic of Armenia" },
    { "code": "AO", "name": "The Republic of Angola" },
    { "code": "AQ", "name": "All land and ice shelves south of the 60th parallel south" },
    { "code": "AR", "name": "The Argentine Republic" },
    { "code": "AS", "name": "The Territory of American Samoa" },
    { "code": "AT", "name": "The Republic of Austria" },
    { "code": "AU", "name": "The Commonwealth of Australia" },
    { "code": "AW", "name": "Aruba" },
    { "code": "AX", "name": "Åland" },
    { "code": "AZ", "name": "The Republic of Azerbaijan" },
    { "code": "BA", "name": "Bosnia and Herzegovina" },
    { "code": "BB", "name": "Barbados" },
    { "code": "BD", "name": "The People's Republic of Bangladesh" },
    { "code": "BE", "name": "The Kingdom of Belgium" },
    { "code": "BF", "name": "Burkina Faso" },
    { "code": "BG", "name": "The Republic of Bulgaria" },
    { "code": "BH", "name": "The Kingdom of Bahrain" },
    { "code": "BI", "name": "The Republic of Burundi" },
    { "code": "BJ", "name": "The Republic of Benin" },
    { "code": "BL", "name": "The Collectivity of Saint-Barthélemy" },
    { "code": "BM", "name": "Bermuda" },
    { "code": "BN", "name": "The Nation of Brunei, the Abode of Peace" },
    { "code": "BO", "name": "The Plurinational State of Bolivia" },
    { "code": "BQ", "name": "Bonaire, Sint Eustatius and Saba" },
    { "code": "BR", "name": "The Federative Republic of Brazil" },
    { "code": "BS", "name": "The Commonwealth of The Bahamas" },
    { "code": "BT", "name": "The Kingdom of Bhutan" },
    { "code": "BV", "name": "Bouvet Island" },
    { "code": "BW", "name": "The Republic of Botswana" },
    { "code": "BY", "name": "The Republic of Belarus" },
    { "code": "BZ", "name": "Belize" },
    { "code": "CA", "name": "Canada" },
    { "code": "CC", "name": "The Territory of Cocos (Keeling) Islands" },
    { "code": "CD", "name": "The Democratic Republic of the Congo" },
    { "code": "CF", "name": "The Central African Republic" },
    { "code": "CG", "name": "The Republic of the Congo" },
    { "code": "CH", "name": "The Swiss Confederation" },
    { "code": "CI", "name": "The Republic of Côte d'Ivoire" },
    { "code": "CK", "name": "The Cook Islands" },
    { "code": "CL", "name": "The Republic of Chile" },
    { "code": "CM", "name": "The Republic of Cameroon" },
    { "code": "CN", "name": "The People's Republic of China" },
    { "code": "CO", "name": "The Republic of Colombia" },
    { "code": "CR", "name": "The Republic of Costa Rica" },
    { "code": "CU", "name": "The Republic of Cuba" },
    { "code": "CV", "name": "The Republic of Cabo Verde" },
    { "code": "CW", "name": "The Country of Curaçao" },
    { "code": "CX", "name": "The Territory of Christmas Island" },
    { "code": "CY", "name": "The Republic of Cyprus" },
    { "code": "CZ", "name": "The Czech Republic" },
    { "code": "DE", "name": "The Federal Republic of Germany" },
    { "code": "DJ", "name": "The Republic of Djibouti" },
    { "code": "DK", "name": "The Kingdom of Denmark" },
    { "code": "DM", "name": "The Commonwealth of Dominica" },
    { "code": "DO", "name": "The Dominican Republic" },
    { "code": "DZ", "name": "The People's Democratic Republic of Algeria" },
    { "code": "EC", "name": "The Republic of Ecuador" },
    { "code": "EE", "name": "The Republic of Estonia" },
    { "code": "EG", "name": "The Arab Republic of Egypt" },
    { "code": "EH", "name": "The Sahrawi Arab Democratic Republic" },
    { "code": "ER", "name": "The State of Eritrea" },
    { "code": "ES", "name": "The Kingdom of Spain" },
    { "code": "ET", "name": "The Federal Democratic Republic of Ethiopia" },
    { "code": "FI", "name": "The Republic of Finland" },
    { "code": "FJ", "name": "The Republic of Fiji" },
    { "code": "FK", "name": "The Falkland Islands" },
    { "code": "FM", "name": "The Federated States of Micronesia" },
    { "code": "FO", "name": "The Faroe Islands" },
    { "code": "FR", "name": "The French Republic" },
    { "code": "GA", "name": "The Gabonese Republic" },
    { "code": "GB", "name": "The United Kingdom of Great Britain and Northern Ireland" },
    { "code": "GD", "name": "Grenada" },
    { "code": "GE", "name": "Georgia" },
    { "code": "GF", "name": "Guyane" },
    { "code": "GG", "name": "The Bailiwick of Guernsey" },
    { "code": "GH", "name": "The Republic of Ghana" },
    { "code": "GI", "name": "Gibraltar" },
    { "code": "GL", "name": "Kalaallit Nunaat" },
    { "code": "GM", "name": "The Republic of The Gambia" },
    { "code": "GN", "name": "The Republic of Guinea" },
    { "code": "GP", "name": "Guadeloupe" },
    { "code": "GQ", "name": "The Republic of Equatorial Guinea" },
    { "code": "GR", "name": "The Hellenic Republic" },
    { "code": "GS", "name": "South Georgia and the South Sandwich Islands" },
    { "code": "GT", "name": "The Republic of Guatemala" },
    { "code": "GU", "name": "The Territory of Guam" },
    { "code": "GW", "name": "The Republic of Guinea-Bissau" },
    { "code": "GY", "name": "The Co-operative Republic of Guyana" },
    { "code": "HK", "name": "The Hong Kong Special Administrative Region of China[10]" },
    { "code": "HM", "name": "The Territory of Heard Island and McDonald Islands" },
    { "code": "HN", "name": "The Republic of Honduras" },
    { "code": "HR", "name": "The Republic of Croatia" },
    { "code": "HT", "name": "The Republic of Haiti" },
    { "code": "HU", "name": "Hungary" },
    { "code": "ID", "name": "The Republic of Indonesia" },
    { "code": "IE", "name": "Ireland" },
    { "code": "IL", "name": "The State of Israel" },
    { "code": "IM", "name": "The Isle of Man" },
    { "code": "IN", "name": "The Republic of India" },
    { "code": "IO", "name": "The British Indian Ocean Territory" },
    { "code": "IQ", "name": "The Republic of Iraq" },
    { "code": "IR", "name": "The Islamic Republic of Iran" },
    { "code": "IS", "name": "Iceland" },
    { "code": "IT", "name": "The Italian Republic" },
    { "code": "JE", "name": "The Bailiwick of Jersey" },
    { "code": "JM", "name": "Jamaica" },
    { "code": "JO", "name": "The Hashemite Kingdom of Jordan" },
    { "code": "JP", "name": "Japan" },
    { "code": "KE", "name": "The Republic of Kenya" },
    { "code": "KG", "name": "The Kyrgyz Republic" },
    { "code": "KH", "name": "The Kingdom of Cambodia" },
    { "code": "KI", "name": "The Republic of Kiribati" },
    { "code": "KM", "name": "The Union of the Comoros" },
    { "code": "KN", "name": "Saint Kitts and Nevis" },
    { "code": "KP", "name": "The Democratic People's Republic of Korea" },
    { "code": "KR", "name": "The Republic of Korea" },
    { "code": "KW", "name": "The State of Kuwait" },
    { "code": "KY", "name": "The Cayman Islands" },
    { "code": "KZ", "name": "The Republic of Kazakhstan" },
    { "code": "LA", "name": "The Lao People's Democratic Republic" },
    { "code": "LB", "name": "The Lebanese Republic" },
    { "code": "LC", "name": "Saint Lucia" },
    { "code": "LI", "name": "The Principality of Liechtenstein" },
    { "code": "LK", "name": "The Democratic Socialist Republic of Sri Lanka" },
    { "code": "LR", "name": "The Republic of Liberia" },
    { "code": "LS", "name": "The Kingdom of Lesotho" },
    { "code": "LT", "name": "The Republic of Lithuania" },
    { "code": "LU", "name": "The Grand Duchy of Luxembourg" },
    { "code": "LV", "name": "The Republic of Latvia" },
    { "code": "LY", "name": "The State of Libya" },
    { "code": "MA", "name": "The Kingdom of Morocco" },
    { "code": "MC", "name": "The Principality of Monaco" },
    { "code": "MD", "name": "The Republic of Moldova" },
    { "code": "ME", "name": "Montenegro" },
    { "code": "MF", "name": "The Collectivity of Saint-Martin" },
    { "code": "MG", "name": "The Republic of Madagascar" },
    { "code": "MH", "name": "The Republic of the Marshall Islands" },
    { "code": "MK", "name": "The Republic of North Macedonia[12]" },
    { "code": "ML", "name": "The Republic of Mali" },
    { "code": "MM", "name": "The Republic of the Union of Myanmar" },
    { "code": "MN", "name": "Mongolia" },
    { "code": "MO", "name": "The Macao Special Administrative Region of China[11]" },
    { "code": "MP", "name": "The Commonwealth of the Northern Mariana Islands" },
    { "code": "MQ", "name": "Martinique" },
    { "code": "MR", "name": "The Islamic Republic of Mauritania" },
    { "code": "MS", "name": "Montserrat" },
    { "code": "MT", "name": "The Republic of Malta" },
    { "code": "MU", "name": "The Republic of Mauritius" },
    { "code": "MV", "name": "The Republic of Maldives" },
    { "code": "MW", "name": "The Republic of Malawi" },
    { "code": "MX", "name": "The United Mexican States" },
    { "code": "MY", "name": "Malaysia" },
    { "code": "MZ", "name": "The Republic of Mozambique" },
    { "code": "NA", "name": "The Republic of Namibia" },
    { "code": "NC", "name": "New Caledonia" },
    { "code": "NE", "name": "The Republic of the Niger" },
    { "code": "NF", "name": "The Territory of Norfolk Island" },
    { "code": "NG", "name": "The Federal Republic of Nigeria" },
    { "code": "NI", "name": "The Republic of Nicaragua" },
    { "code": "NL", "name": "The Kingdom of the Netherlands" },
    { "code": "NO", "name": "The Kingdom of Norway" },
    { "code": "NP", "name": "The Federal Democratic Republic of Nepal" },
    { "code": "NR", "name": "The Republic of Nauru" },
    { "code": "NU", "name": "Niue" },
    { "code": "NZ", "name": "New Zealand" },
    { "code": "OM", "name": "The Sultanate of Oman" },
    { "code": "PA", "name": "The Republic of Panamá" },
    { "code": "PE", "name": "The Republic of Perú" },
    { "code": "PF", "name": "French Polynesia" },
    { "code": "PG", "name": "The Independent State of Papua New Guinea" },
    { "code": "PH", "name": "The Republic of the Philippines" },
    { "code": "PK", "name": "The Islamic Republic of Pakistan" },
    { "code": "PL", "name": "The Republic of Poland" },
    { "code": "PM", "name": "The Overseas Collectivity of Saint-Pierre and Miquelon" },
    { "code": "PN", "name": "The Pitcairn, Henderson, Ducie and Oeno Islands" },
    { "code": "PR", "name": "The Commonwealth of Puerto Rico" },
    { "code": "PS", "name": "The State of Palestine" },
    { "code": "PT", "name": "The Portuguese Republic" },
    { "code": "PW", "name": "The Republic of Palau" },
    { "code": "PY", "name": "The Republic of Paraguay" },
    { "code": "QA", "name": "The State of Qatar" },
    { "code": "RE", "name": "Réunion" },
    { "code": "RO", "name": "Romania" },
    { "code": "RS", "name": "The Republic of Serbia" },
    { "code": "RU", "name": "The Russian Federation" },
    { "code": "RW", "name": "The Republic of Rwanda" },
    { "code": "SA", "name": "The Kingdom of Saudi Arabia" },
    { "code": "SB", "name": "The Solomon Islands" },
    { "code": "SC", "name": "The Republic of Seychelles" },
    { "code": "SD", "name": "The Republic of the Sudan" },
    { "code": "SE", "name": "The Kingdom of Sweden" },
    { "code": "SG", "name": "The Republic of Singapore" },
    { "code": "SH", "name": "Saint Helena, Ascension and Tristan da Cunha" },
    { "code": "SI", "name": "The Republic of Slovenia" },
    { "code": "SJ", "name": "Svalbard and Jan Mayen" },
    { "code": "SK", "name": "The Slovak Republic" },
    { "code": "SL", "name": "The Republic of Sierra Leone" },
    { "code": "SM", "name": "The Republic of San Marino" },
    { "code": "SN", "name": "The Republic of Senegal" },
    { "code": "SO", "name": "The Federal Republic of Somalia" },
    { "code": "SR", "name": "The Republic of Suriname" },
    { "code": "SS", "name": "The Republic of South Sudan" },
    { "code": "ST", "name": "The Democratic Republic of São Tomé and Príncipe" },
    { "code": "SV", "name": "The Republic of El Salvador" },
    { "code": "SX", "name": "Sint Maarten" },
    { "code": "SY", "name": "The Syrian Arab Republic" },
    { "code": "SZ", "name": "The Kingdom of Eswatini" },
    { "code": "TC", "name": "The Turks and Caicos Islands" },
    { "code": "TD", "name": "The Republic of Chad" },
    { "code": "TF", "name": "The French Southern and Antarctic Lands" },
    { "code": "TG", "name": "The Togolese Republic" },
    { "code": "TH", "name": "The Kingdom of Thailand" },
    { "code": "TJ", "name": "The Republic of Tajikistan" },
    { "code": "TK", "name": "Tokelau" },
    { "code": "TL", "name": "The Democratic Republic of Timor-Leste" },
    { "code": "TM", "name": "Turkmenistan" },
    { "code": "TN", "name": "The Republic of Tunisia" },
    { "code": "TO", "name": "The Kingdom of Tonga" },
    { "code": "TR", "name": "The Republic of Turkey" },
    { "code": "TT", "name": "The Republic of Trinidad and Tobago" },
    { "code": "TV", "name": "Tuvalu" },
    { "code": "TW", "name": "The Republic of China" },
    { "code": "TZ", "name": "The United Republic of Tanzania" },
    { "code": "UA", "name": "Ukraine" },
    { "code": "UG", "name": "The Republic of Uganda" },
    { "code": "UM", "name": "Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island" },
    { "code": "US", "name": "The United States of America" },
    { "code": "UY", "name": "The Oriental Republic of Uruguay" },
    { "code": "UZ", "name": "The Republic of Uzbekistan" },
    { "code": "VA", "name": "The Holy See" },
    { "code": "VC", "name": "Saint Vincent and the Grenadines" },
    { "code": "VE", "name": "The Bolivarian Republic of Venezuela" },
    { "code": "VG", "name": "The Virgin Islands" },
    { "code": "VI", "name": "The Virgin Islands of the United States" },
    { "code": "VN", "name": "The Socialist Republic of Viet Nam" },
    { "code": "VU", "name": "The Republic of Vanuatu" },
    { "code": "WF", "name": "The Territory of the Wallis and Futuna Islands" },
    { "code": "WS", "name": "The Independent State of Samoa" },
    { "code": "YE", "name": "The Republic of Yemen" },
    { "code": "YT", "name": "The Department of Mayotte" },
    { "code": "ZA", "name": "The Republic of South Africa" },
    { "code": "ZM", "name": "The Republic of Zambia" },
    { "code": "ZW", "name": "The Republic of Zimbabwe" },
];