export const builderTemplate: any[] = [
  {
    templateId: 'A001',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 1 - Standard',
    json: 'attendee-workflow-1.json',
    url: '/workflow1/attendee/',
    includingPages:
      'Login, personal information, demographic, registration category, qualifications, sessions & events, review & payment information, registration confirmation, dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/attendee-1-standard.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'scholarship-layout/scholarship-donation',
        displayName: 'Add-On Page',
        enable: true,
      },
      {
        page: 'reg-review-layout/registration-review',
        displayName: 'Registration Review Dashboard(pre-payment)',
        enable: false,
      },
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A002',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 1 - Chicago Bears',
    json: 'attendee-workflow-1-chicago-bears.json',
    url: '/workflow1/attendee/',
    includingPages:
      'Login, personal information, demographic, registration category, qualifications, sessions & events, review & payment information, registration confirmation, dashboard',
    checked: false,
    themeType: 'Chicago Bears',
    img: 'assets/templateImages/attendee-1-chicago.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'scholarship-layout/scholarship-donation',
        displayName: 'Add-On Page',
        enable: true,
      },
      {
        page: 'reg-review-layout/registration-review',
        displayName: 'Registration Review Dashboard(pre-payment)',
        enable: false,
      },
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A003',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 2 - Standard',
    json: 'attendee-workflow-2.json',
    url: '/workflow2/attendee/',
    includingPages:
      'Login, personal information, Reg Type package page, demographics page, sessions & events, review & payment information, registration confirmation, dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/attendee-2-standard.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A004',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 2 - Chicago Bears',
    json: 'attendee-workflow-2-chicago-bears.json',
    url: '/workflow2/attendee/',
    includingPages:
      'Login, personal information, Reg Type package page, demographics page, sessions & events, review & payment information, registration confirmation, dashboard',
    checked: false,
    themeType: 'Chicago Bears',
    img: 'assets/templateImages/attendee-2-chicago.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A005',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 3 - Standard',
    json: 'attendee-workflow-3.json',
    url: '/workflow3/attendee/',
    includingPages: 'No demographics page',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/attendee-3-standard.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A006',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 3 - Chicago Bears',
    json: 'attendee-workflow-3-chicago-bears.json',
    url: '/workflow3/attendee/',
    includingPages: 'No demographics page',
    checked: false,
    themeType: 'Chicago Bears',
    img: 'assets/templateImages/attendee-3-chicago.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A007',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 4 - Standard',
    json: 'attendee-workflow-4.json',
    url: '/workflow4/attendee/',
    includingPages:
      'Login, personal information, demographic, Licensing Information, registration category, review & payment information, registration confirmation, & dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/attendee-4-standard.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'license-layout/information',
        displayName: 'Licensing Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A008',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 4 - Chicago Bears',
    json: 'attendee-workflow-4-chicago-bears.json',
    url: '/workflow4/attendee/',
    includingPages:
      'Login, personal information, demographic, Licensing Information, registration category, review & payment information, registration confirmation, & dashboard',
    checked: false,
    themeType: 'Chicago Bears',
    img: 'assets/templateImages/attendee-4-chicago.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'license-layout/information',
        displayName: 'Licensing Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A009',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 5 - Standard',
    json: 'attendee-workflow-5.json',
    url: '/workflow5/attendee/',
    includingPages:
      'Login, personal information, demographic, Licensing Information, registration category, review & payment information, registration confirmation, & dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/attendee-5-standard.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'license-layout/information',
        displayName: 'Licensing Information',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'scholarship-layout/scholarship-donation',
        displayName: 'Add-On Page',
        enable: true,
      },
      {
        page: 'reg-review-layout/registration-review',
        displayName: 'Registration Review Dashboard(pre-payment)',
        enable: false,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A010',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 5 - Chicago Bears',
    json: 'attendee-workflow-5-chicago-bears.json',
    url: '/workflow5/attendee/',
    includingPages:
      'Login, personal information, demographic, Licensing Information, registration category, review & payment information, registration confirmation, & dashboard',
    checked: false,
    themeType: 'Chicago Bears',
    img: 'assets/templateImages/attendee-5-chicago.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'license-layout/information',
        displayName: 'Licensing Information',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'scholarship-layout/scholarship-donation',
        displayName: 'Add-On Page',
        enable: true,
      },
      {
        page: 'reg-review-layout/registration-review',
        displayName: 'Registration Review Dashboard(pre-payment)',
        enable: false,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A011',
    templateType: 'Attendee',
    templateName: 'Reg Workflow 6 - Standard',
    json: 'attendee-workflow-6.json',
    url: '/workflow6/attendee/',
    includingPages:
      'Welcome, personal information, registration package, upload credential document, session, review registration, payment, registration confirmation, dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/attendee-6-standard.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review Information',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'payment-layout/payment-Information',
        displayName: 'Payment Information',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A012',
    templateType: 'Attendee',
    templateName: 'NACDS Workflow',
    json: 'NACDS-workflow.json',
    url: '/NACDS/attendee/',
    includingPages:
      'Welcome, Individual Lookup, personal information, registration package, upload credential document, session, review registration, payment, registration confirmation, dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/NACDS-theme.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      // {page: 'reg-review-layout/registration-review', displayName: 'Registration Review', enable: false},
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A013',
    templateType: 'Attendee',
    templateName: 'NBAA Workflow',
    json: 'NBAA-workflow.json',
    url: '/NBAA/attendee/',
    includingPages:
      'NBAA SSO, personal information, registration package, upload credential document, session, Scholarship Donation, review registration, payment, registration confirmation, dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/NBAA-theme.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'scholarship-layout/scholarship-donation',
        displayName: 'Add-On Page',
        enable: true,
      },
      {
        page: 'reg-review-layout/registration-review',
        displayName: 'Registration Review Dashboard(pre-payment)',
        enable: false,
      },
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'A014',
    templateType: 'Attendee',
    templateName: 'Rotary Workflow',
    json: 'Rotary-workflow.json',
    url: '/Rotary/attendee/',
    includingPages:
      'Rotary SSO, personal information, registration package, upload credential document, session, Scholarship Donation, review registration, payment, registration confirmation, dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/Rotary-theme.png',
    pages: [
      {
        page: 'personal-layout/personal',
        displayName: 'Personal Information',
        enable: true,
      },
      {
        page: 'demographic-layout/demographic-Information',
        displayName: 'Demographic Information',
        enable: true,
      },
      {
        page: 'registration/registration',
        displayName: 'Registration Category & Package',
        enable: true,
      },
      {
        page: 'qualifications-layout/Qualifications',
        displayName: 'Qualifications',
        enable: true,
      },
      {
        page: 'session-layout/Session-Events',
        displayName: 'Session & Events',
        enable: true,
      },
      {
        page: 'scholarship-layout/scholarship-donation',
        displayName: 'Add-On Page',
        enable: true,
      },
      {
        page: 'reg-review-layout/registration-review',
        displayName: 'Registration Review Dashboard(pre-payment)',
        enable: false,
      },
      {
        page: 'review-layout/Review-Information',
        displayName: 'Review and Payment',
        enable: true,
      },
      {
        page: 'registration-confirmation/confirmation',
        displayName: 'Registration Confirmation',
        enable: true,
      },
      {
        page: 'dashboard-layout/dashboard',
        displayName: 'Registration Dashboard(post-payment)',
        enable: true,
      },
    ],
  },
  {
    templateId: 'E001',
    templateType: 'Exhibitor',
    templateName: 'Exhibitor Standard',
    json: 'exhibitor-workflow-1.json',
    url: '/workflow1/exhibitor/',
    includingPages: '',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/exhibitor-1-standard.png',
    pages: [],
  },
  {
    templateId: 'E002',
    templateType: 'Exhibitor',
    templateName: 'Exhibitor Chicago Bears',
    json: 'exhibitor-workflow-1-chicago-bears.json',
    url: '/workflow1/exhibitor/',
    includingPages: '',
    checked: false,
    themeType: 'Chicago Bears',
    img: 'assets/templateImages/exhibitor-1-chicago.png',
    pages: [],
  },
  {
    templateId: 'O001',
    templateType: 'Organizer',
    templateName: 'Organizer Standard',
    json: 'organizer-workflow-1.json',
    url: '/workflow1/organizer/',
    includingPages: 'Login, Dashboard, Reports',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/organizer-1-standard.png',
    pages: [],
  },
  {
    templateId: 'O002',
    templateType: 'Organizer',
    templateName: 'Organizer Chicago Bears',
    json: 'organizer-workflow-1-chicago-bears.json',
    url: '/workflow1/organizer/',
    includingPages: 'Login, Dashboard, Reports',
    checked: false,
    themeType: 'Chicago Bears',
    img: 'assets/templateImages/organizer-1-chicago.png',
    pages: [],
  },
  {
    templateId: 'C001',
    templateType: 'Commander',
    templateName: 'Commander Portal',
    json: 'commander-portal.json',
    url: '/commander-login/commander-login/',
    includingPages: 'Login, Dashboard',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/organizer-1-standard.png',
    pages: [],
  },
  {
    templateId: 'P001',
    templateType: 'Event Portal',
    templateName: 'Event Portal Workflow',
    json: 'event-portal.json',
    url: '/',
    includingPages: 'Home, Speakers, Schedule, Location, Get Tickets',
    checked: false,
    themeType: 'Standard',
    img: 'assets/templateImages/event-portal.png',
    pages: [],
  },
];
