export const OptionTypes = [
  { code: 'don', description: 'Donation' },
  { code: 'session', description: 'General Session' },
  { code: 'cancel', description: 'Cancel session' },
  { code: 'eventSpecial', description: 'Special event' },
  { code: 'salesNovelty', description: 'Novelty sales' },
  { code: 'salesFashion', description: 'Fashion sales' },
  { code: 'techncal', description: 'Technical session' },
  { code: 'wrkshop', description: 'Workshop session' },
  { code: 'lab', description: 'Lab session' },
  { code: 'exam', description: 'Testing session' },
  { code: 'elective', description: 'Elective session' },
  { code: 'trackCourse', description: 'Course track' },
  { code: 'trackSession', description: 'Tracking session' },
  { code: 'eventExcursion', description: 'Excursion' },
  { code: 'game', description: 'Game session' },
  { code: 'mbrshipRenewal', description: 'membership renewal' },
  { code: 'forum', description: 'Forum session' },
  { code: 'salesRetailProduct', description: 'retail product' },
  { code: 'demoProduct', description: 'Product demo' },
  { code: 'demoeExhibitor', description: 'Exhibitor session' },
  { code: 'fee', description: 'Service fee' },
  { code: 'tax', description: 'Taxed items' },
  { code: 'salesProducts', description: 'Products for Sale' },
  { code: 'gen', description: 'Non classified sessions' },
  { code: 'event', description: '' },
  { code: 'sales', description: '' },
  { code: 'demo', description: '' },
  { code: 'mbrship', description: '' },
  { code: 'merchandise', description: 'Merchandise' },
];
