import { PageData, WorkflowData } from '../../interfaces/customPage';

const attendeePageList: PageData[] = [
  {
    label: 'Personal Info',
    name: 'personal_info',
    sectionsList: [
      {
        label: 'Personal Information',
        name: 'personal_info',
        fieldsList: [
          {
            label: 'Membership Status',
            name: 'memberShipStatus',
            type: 'input_free',
            value: 'Non Member',
            static: true,
            disable: true,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Last Name',
            name: 'lastName',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'First Name',
            name: 'firstName',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Middle Initial',
            name: 'middleInitial',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Company Name',
            name: 'companyName',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          // {
          //     label: "Job Title",
          //     name: "jobTitle",
          //     type: "select",
          //     value: "Vet",
          //     static: false,
          //     disable: false,
          //     required: true,
          //     visible: true
          // },
        ],
      },
      {
        label: 'Address Information',
        name: 'address_info',
        fieldsList: [
          {
            label: 'Department',
            name: 'department',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Street',
            name: 'street',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'PO Box',
            name: 'poBox',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Postal Code',
            name: 'zip',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'City',
            name: 'city',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'State',
            name: 'state',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Country',
            name: 'country',
            type: 'select',
            value: 'US',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Phone Number',
            name: 'workNumber',
            type: 'input_phone',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Fax Number',
            name: 'faxNumber',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Cell Number',
            name: 'mobileNumber',
            type: 'input_phone',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
          },
          {
            label:
              'Check here if you have special dietary needs and list requirements:',
            name: 'specialDietary',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
          },
        ],
      },
      {
        label: 'Registration Dashboard Information',
        name: 'reg_dash_info',
        fieldsList: [
          {
            label: 'Email Address',
            name: 'email',
            type: 'input_email',
            value: '',
            static: false,
            disable: true,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label:
              'Would you like your confirmation emailed to an additional address? If so, Enter email address below.',
            name: 'addEmail',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
        ],
      },
      {
        label: 'Other Information',
        name: 'other_info',
        fieldsList: [
          {
            label: 'Special Accommodation',
            name: 'specialAccomodationText',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 1',
            name: 'commercialPreference1Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 2',
            name: 'commercialPreference2Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Terms and Conditions',
            name: 'termsAndConditions',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
        ],
      },
      {
        label: 'Registration Account Information',
        name: 'reg_account_info',
        fieldsList: [
          {
            label: 'E-mail Address',
            name: 'email',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Confirm E-mail Address',
            name: 'confirmEmail',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Password',
            name: 'password',
            type: 'input_password',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Confirm Password',
            name: 'confirmPassword',
            type: 'input_password',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
      },
    ],
  },
  {
    label: 'Header',
    name: 'header',
    sectionsList: [
      {
        label: 'Header',
        name: 'header',
        fieldsList: [
          {
            label: 'Facebook',
            name: 'facebook',
            value: 'https://facebook.com/',
          },
          {
            label: 'Twitter',
            name: 'twitter',
            value: 'https://twitter.com/',
          },
          {
            label: 'Linkedin',
            name: 'linkedin',
            value: 'https://linkedin.com/',
          },
          {
            label: 'Youtube',
            name: 'youtube',
            value: 'https://youtube.com/',
          },
          {
            label: 'Contact Us: Question about registration',
            name: 'questionRegistration',
            value: 'Contact Us: Question about registration',
          },
          {
            label: 'Contact Us: Question about membership',
            name: 'questionMembership',
            value: 'Contact Us: Question about membership',
          },
          {
            label: 'Show Policies',
            name: 'showPolicy',
            value: 'test policy',
          },
          {
            label: 'Cancellation Policy',
            name: 'cancellationPolicy',
            value: 'test cancellation',
          },
          {
            label: 'Harassment Policy',
            name: 'CSIHarassmentStatement',
            value: 'test harassement statement',
          },
        ],
      },
    ],
  },
  {
    label: 'Review & Payment',
    name: 'review_payment',
    sectionsList: [
      {
        label: 'Payment Notice',
        name: 'payment_notice',
        fieldsList: [
          {
            label: 'Payment Notice',
            name: 'payment_notice',
            value:
              'Notice! All registration fees will be applied to the card below. By submitting this registration, I authorize  to charge my credit card account the applicable fees for the registrations (badge requests) I processed during this online session',
          },
        ],
      },
      {
        label: 'Terms and Conditions',
        name: 'terms_conditions',
        fieldsList: [
          {
            label: 'Terms and Conditions',
            name: 'terms_conditions',
            value: '',
            // 'By registering for this conference, I agree that  and its vendors assisting in conference operations may retain and use my contact information to send me information and materials concerning .  My contact information will be deleted from  database within two years of the conclusion of the conference, unless I have registered for , am a member of , or have otherwise consented to receive emails from . All cancellation must be received in writing . If a written request of cancellation is received at the  office prior to 19 August 2022, the registration fee, less a $100 administrative fee, will be refunded after the meeting. Refund requests after 19 August 2022, will not be honored. By presenting your badge for scanning at any  educational session or at a booth or event in the Exhibition Hall, you agree that your contact information may be provided to the session sponsor or exhibitor for marketing purposes',
          },
        ],
      },
      {
        label: 'Cancellation Conditions',
        name: 'cancellation_conditions',
        fieldsList: [
          {
            label: 'Cancellation Conditions',
            name: 'cancellation_conditions',
            value:
              'Example: Cancel before February 1st for full refund. After February 1st, cancellation is not allowed.',
          },
        ],
      },
      {
        label: 'Other Information Payment',
        name: 'other_info_payment',
        fieldsList: [
          {
            label: 'Special Accommodation',
            name: 'specialAccomodationText',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 1',
            name: 'commercialPreference1Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 2',
            name: 'commercialPreference2Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Terms and Conditions',
            name: 'termsAndConditions',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
        ],
      },
      {
        label: 'Footer',
        name: 'review_footer',
        fieldsList: [
          {
            label: 'Footer 1',
            name: 'review_footer1',
            value: 'Sample Review Footer 1',
          },
          {
            label: 'Footer 2',
            name: 'review_footer2',
            value: 'Sample Review Footer 2',
          },
        ],
      },
    ],
  },
  {
    label: 'Registration Review',
    name: 'registration_review',
    sectionsList: [
      {
        label: 'Other Information',
        name: 'other_info_dashboard',
        fieldsList: [
          {
            label: 'Special Accommodation',
            name: 'specialAccomodationText',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 1',
            name: 'commercialPreference1Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 2',
            name: 'commercialPreference2Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Terms and Conditions',
            name: 'termsAndConditions',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
        ],
      },
      {
        label: 'Terms and Conditions',
        name: 'terms_conditions',
        editType: "text-editor",
        fieldsList: [
          {
            label: 'Terms and Conditions',
            name: 'terms_conditions',
            value: '',
          },
        ],
      },
    ],
  },
  {
    label: 'Login',
    name: 'login',
    sectionsList: [
      {
        label: 'Login Header',
        name: 'login_header',
        fieldsList: [
          {
            label: 'Header Text 1',
            name: 'header_text_1',
            value:
              'We are working closely with the venue facility, and all relevant local authorities to ensure that all locals, regional and federal safety all attendee is our priority. As findings develop over the coming months, our approach will continue to ad.',
          },
          {
            label: 'Header Text 2',
            name: 'header_text_2',
            value:
              'Login below to register for Vet Show Austin 2023 or access your Attendee Dashboard. From the Dashboard you can do the following: View/Search Exhibitors, make Appointments with Exhibitor, Review/Update your Record, Re-send a Confirmation, Invite Colleagues, View you badge.',
          },
        ],
      },
      {
        label: 'Login Section',
        name: 'login_section',
        fieldsList: [
          {
            label: 'Login Form Title',
            name: 'login_form_title',
            value: 'ALREADY REGISTERED',
          },
          {
            label: 'Login Form Description',
            name: 'login_form_desc',
            value:
              'If you are registered, enter your email and password below:',
          },
        ],
      },
      {
        label: 'Login Fields',
        name: 'login_fields',
        fieldsList: [
          {
            label: 'Email',
            name: 'emailAddr',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Password',
            name: 'password',
            type: 'input_password',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
      },
      {
        label: 'Register Section',
        name: 'register_section',
        fieldsList: [
          {
            label: 'Register Form Title',
            name: 'register_form_title',
            value: 'NEW REGISTRATION',
          },
          {
            label: 'Register Form Description',
            name: 'register_form_desc',
            value: 'Please complete fields below:',
          },
        ],
      },
      {
        label: 'Register Fields',
        name: 'register_fields',
        fieldsList: [
          {
            label: 'Email',
            name: 'emailAddr',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Password',
            name: 'password',
            type: 'input_password',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'First Name',
            name: 'nameFirst',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Last Name',
            name: 'nameLast',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Postal Code',
            name: 'postalCode',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
      },
    ],
  },
  {
    label: 'Session',
    name: 'session',
    sectionsList: [
      {
        label: 'Header',
        name: 'session_header',
        fieldsList: [
          {
            label: 'Header',
            name: 'session_header',
            value: 'Sample Session Header',
          },
        ],
      },
      {
        label: 'Footer',
        name: 'session_footer',
        fieldsList: [
          {
            label: 'Footer',
            name: 'session_footer',
            value: 'Sample Session Footer',
          },
        ],
      },
      {
        label: 'Other Information',
        name: 'other_info',
        fieldsList: [
          {
            label: 'Special Accommodation',
            name: 'specialAccomodationText',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 1',
            name: 'commercialPreference1Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 2',
            name: 'commercialPreference2Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Terms and Conditions',
            name: 'termsAndConditions',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
        ],
      },
    ],
  },
  {
    label: 'Add on',
    name: 'add_on',
    sectionsList: [
      {
        label: 'Header',
        name: 'addon_header',
        fieldsList: [
          {
            label: 'Header',
            name: 'addon_header',
            value: 'Sample Add On Header',
          },
        ],
      },
      {
        label: 'Footer',
        name: 'addon_footer',
        fieldsList: [
          {
            label: 'Footer',
            name: 'addon_footer',
            value: 'Sample Add On Footer',
          },
        ],
      },
      {
        label: 'Other Information',
        name: 'other_info',
        fieldsList: [
          {
            label: 'Special Accommodation',
            name: 'specialAccomodationText',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 1',
            name: 'commercialPreference1Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Commercial Preference 2',
            name: 'commercialPreference2Text',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Terms and Conditions',
            name: 'termsAndConditions',
            type: 'checkbox',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
        ],
      },
    ],
  },
];

const attendeeMandatoryFields: String[] = [
  // "firstName",
  // "lastName",
  // "email",
  // "confirmEmail",
  // "password",
  // "confirmPassword"
];

const exBoothMandatoryFields: String[] = [
  // "firstName",
  // "lastName",
  // "email",
  // "title",
];

const ESGMandatoryFields: String[] = [
  // "firstName",
  // "lastName",
  // "email",
  // "confirmEmail",
  // "password",
  // "confirmPassword"
];

const exBoothPageList: PageData[] = [
  {
    label: 'Demographics Collection',
    name: 'demographics_collection',
    sectionsList: [
      {
        label: 'Personal Information',
        name: 'personal_info',
        fieldsList: [
          {
            label: 'Last Name',
            name: 'lastName',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'First Name',
            name: 'firstName',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Company',
            name: 'companyName',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Title',
            name: 'title',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'E-mail Address',
            name: 'email',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Work Phone Number',
            name: 'workNumber',
            type: 'input_phone',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Cell Phone Number',
            name: 'mobileNumber',
            type: 'input_phone',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
        ],
      },
      {
        label: 'Address Information',
        name: 'address_info',
        fieldsList: [
          {
            label: 'Address 1',
            name: 'address1',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Address 2',
            name: 'address2',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
          },
          {
            label: 'Zip/Postal Code',
            name: 'zip',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'City',
            name: 'city',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'State/Province',
            name: 'state',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Country',
            name: 'country',
            type: 'select',
            value: 'US',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
      },
    ],
  },
];
const showOrganizerPageList: PageData[] = [
  {
    label: 'Data Manager',
    name: 'new-registration',
    sectionsList: [
      {
        label: 'Badge Type/Registration Fees',
        name: 'badge-type',
        fieldsList: [
          {
            label: 'Exhibitor Number',
            name: 'exhUid',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            lookup: true,
            column: 1,
          },
          {
            label: 'RegTypeEvtCode',
            name: 'regTypeEvtCode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Reg Code',
            name: 'regCode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Reg2EvtCode',
            name: 'reg2EvtCode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'Reg3EvtCode',
            name: 'reg3EvtCode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'Reg4EvtCode',
            name: 'reg4EvtCode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'text1',
            name: 'text1',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'text2',
            name: 'text2',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'Membership Status',
            name: 'memberStatus',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Qualification',
            name: 'qualificationStatus',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'Geocode',
            name: 'geocode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'Country',
            name: 'country',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 1,
          },
          {
            label: 'Promo Code',
            name: 'promoCode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Rate',
            name: 'rate',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'text3',
            name: 'text3',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'text4',
            name: 'text4',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'text5',
            name: 'text5',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'text6',
            name: 'text6',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'text7',
            name: 'text7',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'text8',
            name: 'text8',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'No Text Messages',
            name: 'noMessage',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'Distinguished Fellow',
            name: 'distinguishedFellow',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'Show Type',
            name: 'showType',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'Missing Letter',
            name: 'missingLetter',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'Exhibitor Confirmation',
            name: 'confirmation',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'Faculty',
            name: 'faculty',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'Source Code',
            name: 'sourceCode',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: false,
            column: 2,
          },
          {
            label: 'RegType',
            name: 'regType',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: false,
            visible: true,
            isActive: true,
            column: 3,
          },
          {
            label: 'KC Link Flag',
            name: 'linkFlag',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: false,
            visible: true,
            isActive: true,
            column: 3,
          },
          {
            label: 'AOV',
            name: 'aov',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: false,
            visible: true,
            isActive: true,
            column: 3,
          },
          {
            label: 'Member ID',
            name: 'memberId',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: false,
            visible: true,
            isActive: true,
            lookup: true,
            column: 3,
          },
          {
            label: 'RDM',
            name: 'rdm',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: false,
            visible: true,
            isActive: true,
            column: 3,
          },
          {
            label: 'Added By',
            name: 'addedBy',
            type: 'input_free',
            value: '',
            static: false,
            disable: true,
            required: false,
            visible: true,
            isActive: true,
            column: 3,
          },
        ],
      },
      {
        label: 'Badge Information',
        name: 'badge-info',
        fieldsList: [
          {
            label: 'Last Name',
            name: 'lastName',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'First Name',
            name: 'firstName',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Middle Initial',
            name: 'middleInitial',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Company Name',
            name: 'companyName',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Job Title',
            name: 'jobTitle',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Phone Number',
            name: 'workNumber',
            type: 'input_phone',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Cell Number',
            name: 'mobileNumber',
            type: 'input_phone',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'E-mail Address',
            name: 'email',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Confirm E-mail Address',
            name: 'confirmEmail',
            type: 'input_email',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 1,
          },
          {
            label: 'Department',
            name: 'department',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'Street',
            name: 'street',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'PO Box',
            name: 'poBox',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'Postal Code',
            name: 'zip',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'City',
            name: 'city',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'State',
            name: 'state',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'Country',
            name: 'country',
            type: 'select',
            value: '',
            static: false,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'Fax Number',
            name: 'faxNumber',
            type: 'input_free',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 2,
          },
          {
            label: 'Select Photo',
            name: 'photo',
            type: 'img_upload',
            value: '',
            static: false,
            disable: false,
            required: false,
            visible: true,
            isActive: true,
            column: 3,
          },
        ],
      },
    ],
  },
];
const ESGPageList: PageData[] = [
  {
    label: 'Lead Retrieval Order Terms and Condition',
    name: 'lead_retrieval_order_terms_and_condition',
    sectionsList: [
      {
        label: 'Terms and Conditions',
        name: 'terms_and_conditions',
        fieldsList: [
          {
            label: 'Terms and Conditions',
            name: 'TERMS_AND_CONDITIONS',
            type: 'p',
            value: `By completing this lead retrieval order, you agree to be
  held liable for the safekeeping and return of the lead
  retrieval device and its accessories. If the device or
  Bluetooth printer is damaged, lost, or stolen, a
  replacement fee of $500 per item will be charged. If the
  power cord is not returned for any device, a $100
  replacement fee will be charged. If the device is not
  returned within one hour after the show floor closes, a
  $100 late fee will be assessed. All fees will be charged
  to the credit card used when placing the order.
  CompuSystems and atEvent are not liable in the event of
  any hardware or software malfunction, service
  interruption, or loss of saved leads.

  No refunds on the CompuLEAD App or its partner
  products once it has been activated. No refunds on all
  CompuLEAD products or its partner products within 30 days
  of the start of the event or after the event begins.
  Orders canceled before that period are entitled to a full
  refund less a $100 cancellation fee. If the event dates
  change, the original event dates will apply to the refund
  policy. Important Note: If the event officially cancels
  due to COVID-19, you will receive a full refund.`,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
        hidden: null,
      },
    ],
  },
  {
    label: 'CompuLEAD Packages',
    name: 'compulead_packages',
    sectionsList: [
      {
        label: 'CompuLEAD APP Package',
        name: 'compulead_app_package',
        fieldsList: [
          {
            label: 'ON/OFF Package',
            name: 'ON_OFF_PACKAGE',
            type: 'input_free',
            value: true,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Image URL',
            name: 'IMAGE_URL',
            type: 'input_free',
            value:
              'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/f0cfd19f-aa24-45f5-b971-7f1985023615_icon1.PNG',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Learn More',
            name: 'LEARN_MORE',
            type: 'input_free',
            value: 'https://xyz',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Max Quantity',
            name: 'MAX_QUANTITY',
            type: 'input_free',
            value: 100,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Includes Description',
            name: 'DESCRIPTION',
            type: 'p',
            value:
              'App activations, 15 pieces of literature (PDFs up to 5 MB each) and 5 links to videos.',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Base Price/Rate',
            name: 'RATE',
            type: 'input_free',
            value: 370,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Additional Rate',
            name: 'ADDITIONAL_RATE',
            type: 'input_free',
            value: 140,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Date Range',
            name: 'DATE_RANGE',
            type: 'input_free',
            value: 'Early Bird',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Date Range Date',
            name: 'DATE_RANGE_DATE',
            type: 'input_free',
            value: '03/25/2022',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
        hidden: null,
      },
      {
        label: 'CompuLEAD Tablet Package',
        name: 'compulead_tablet_package',
        fieldsList: [
          {
            label: 'ON/Off Package',
            name: 'ON_OFF_PACKAGE',
            type: 'input_free',
            value: true,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Image URL',
            name: 'IMAGE_URL',
            type: 'input_free',
            value:
              'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/8ff1fe40-604a-485c-9b29-396e980467be_icon2.PNG',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Learn More',
            name: 'LEARN_MORE',
            type: 'input_free',
            value: 'https://xyz',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Max Quantity',
            name: 'MAX_QUANTITY',
            type: 'input_free',
            value: 100,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Includes Description',
            name: 'DESCRIPTION',
            type: 'p',
            value:
              'Use of 1 tablet with app activation for duration of show, 15 pieces of literature(PDFs up to 5 MB each), 5 links to videos, user of wireless printer for duration of show and delivery, setup and in-booth techincal training.',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Base Price/Rate',
            name: 'RATE',
            type: 'input_free',
            value: 470,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Additional Rate',
            name: 'ADDITIONAL_RATE',
            type: 'input_free',
            value: 140,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Date Range',
            name: 'DATE_RANGE',
            type: 'input_free',
            value: 'Early Bird',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Date Range Date',
            name: 'DATE_RANGE_DATE',
            type: 'input_free',
            value: '03/25/2022',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
        hidden: null,
      },
      {
        label: 'atEvent',
        name: 'atevent',
        fieldsList: [
          {
            label: 'ON/Off Package',
            name: 'ON_OFF_PACKAGE',
            type: 'input_free',
            value: true,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Image URL',
            name: 'IMAGE_URL',
            type: 'input_free',
            value:
              'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/5c5ba1b6-8d99-4d2d-a4e5-7a173dfad2cc_icon3.PNG',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Learn More',
            name: 'LEARN_MORE',
            type: 'input_free',
            value: 'https://xyz',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Max Quantity',
            name: 'MAX_QUANTITY',
            type: 'input_free',
            value: 100,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Includes Description',
            name: 'DESCRIPTION',
            type: 'ul',
            value: `atEvent mobile lead capture app activation for 3 users |
Customized mapping to you marketing automation or CRM system |
GDPR and CCPA complimant consentat-capture |
Real-time event and user analystics in app |
Event analytics dashboard for 60 days`,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Base Price/Rate',
            name: 'RATE',
            type: 'input_free',
            value: 570,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Additional Rate',
            name: 'ADDITIONAL_RATE',
            type: 'input_free',
            value: 140,
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Date Range',
            name: 'DATE_RANGE',
            type: 'input_free',
            value: 'Early Bird',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
          {
            label: 'Date Range Date',
            name: 'DATE_RANGE_DATE',
            type: 'input_free',
            value: '02/25/2022',
            disable: false,
            required: true,
            visible: true,
            isActive: true,
          },
        ],
        hidden: null,
      },
    ],
  },
  // recommended products
  // {
  //   label: 'CompuLEAD Products',
  //   name: 'compulead_products',
  //   sectionsList: [
  //     {
  //       label: 'CompuLEAD App User Activation',
  //       name: 'compulead_app_user_activation',
  //       fieldsList: [
  //         {
  //           label: 'ON/Off Package',
  //           name: 'ON_OFF_PACKAGE',
  //           // type: null,
  //           value: true,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Image URL',
  //           name: 'IMAGE_URL',
  //           // type: null,
  //           value:
  //             'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/f0cfd19f-aa24-45f5-b971-7f1985023615_icon1.PNG',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Learn More',
  //           name: 'LEARN_MORE',
  //           // type: null,
  //           value: 'https://xyz',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Max Quantity',
  //           name: 'MAX_QUANTITY',
  //           // type: null,
  //           value: 100,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Includes Description',
  //           name: 'DESCRIPTION',
  //           type: 'p',
  //           value: 'App activations, 15 pieces of literature (PDFs up to 5 MB each) and 5 links to videos.',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Base Price/Rate',
  //           name: 'RATE',
  //           // type: null,
  //           value: 370,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Additional Rate',
  //           name: 'ADDITIONAL_RATE',
  //           // type: null,
  //           value: 140,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range',
  //           name: 'DATE_RANGE',
  //           // type: null,
  //           value: 'Early Bird',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range Date',
  //           name: 'DATE_RANGE_DATE',
  //           // type: null,
  //           value: '03/25/2022',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         }
  //       ],
  //       hidden: null,
  //     },
  //     {
  //       label: 'CompuLEAD Tablet',
  //       name: 'compulead_tablet',
  //       fieldsList: [
  //         {
  //           label: 'ON/Off Package',
  //           name: 'ON_OFF_PACKAGE',
  //           // type: null,
  //           value: true,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Image URL',
  //           name: 'IMAGE_URL',
  //           // type: null,
  //           value:
  //             'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/f0cfd19f-aa24-45f5-b971-7f1985023615_icon1.PNG',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Learn More',
  //           name: 'LEARN_MORE',
  //           // type: null,
  //           value: 'https://xyz',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Max Quantity',
  //           name: 'MAX_QUANTITY',
  //           // type: null,
  //           value: 100,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Includes Description',
  //           name: 'DESCRIPTION',
  //           type: 'p',
  //           value: 'App activations, 15 pieces of literature (PDFs up to 5 MB each) and 5 links to videos.',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Base Price/Rate',
  //           name: 'RATE',
  //           // type: null,
  //           value: 370,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Additional Rate',
  //           name: 'ADDITIONAL_RATE',
  //           // type: null,
  //           value: 140,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range',
  //           name: 'DATE_RANGE',
  //           // type: null,
  //           value: 'Early Bird',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range Date',
  //           name: 'DATE_RANGE_DATE',
  //           // type: null,
  //           value: '03/25/2022',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         }
  //       ],
  //       hidden: null,
  //     },
  //     {
  //       label: 'CompuLEAD Kiosk',
  //       name: 'compulead_kiosk',
  //       fieldsList: [
  //         {
  //           label: 'ON/Off Package',
  //           name: 'ON_OFF_PACKAGE',
  //           // type: null,
  //           value: true,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Image URL',
  //           name: 'IMAGE_URL',
  //           // type: null,
  //           value:
  //             'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/f0cfd19f-aa24-45f5-b971-7f1985023615_icon1.PNG',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Learn More',
  //           name: 'LEARN_MORE',
  //           // type: null,
  //           value: 'https://xyz',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Max Quantity',
  //           name: 'MAX_QUANTITY',
  //           // type: null,
  //           value: 100,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Includes Description',
  //           name: 'DESCRIPTION',
  //           type: 'p',
  //           value: 'App activations, 15 pieces of literature (PDFs up to 5 MB each) and 5 links to videos.',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Base Price/Rate',
  //           name: 'RATE',
  //           // type: null,
  //           value: 370,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Additional Rate',
  //           name: 'ADDITIONAL_RATE',
  //           // type: null,
  //           value: 140,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range',
  //           name: 'DATE_RANGE',
  //           // type: null,
  //           value: 'Early Bird',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range Date',
  //           name: 'DATE_RANGE_DATE',
  //           // type: null,
  //           value: '03/25/2022',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         }
  //       ],
  //       hidden: null,
  //     },
  //     {
  //       label: 'CompuLEAD App Unlimited Activations',
  //       name: 'compulead_app_unlimited_activations',
  //       fieldsList: [
  //         {
  //           label: 'ON/Off Package',
  //           name: 'ON_OFF_PACKAGE',
  //           // type: null,
  //           value: true,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Image URL',
  //           name: 'IMAGE_URL',
  //           // type: null,
  //           value:
  //             'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/f0cfd19f-aa24-45f5-b971-7f1985023615_icon1.PNG',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Learn More',
  //           name: 'LEARN_MORE',
  //           // type: null,
  //           value: 'https://xyz',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Max Quantity',
  //           name: 'MAX_QUANTITY',
  //           // type: null,
  //           value: 100,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Includes Description',
  //           name: 'DESCRIPTION',
  //           type: 'p',
  //           value: 'App activations, 15 pieces of literature (PDFs up to 5 MB each) and 5 links to videos.',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Base Price/Rate',
  //           name: 'RATE',
  //           // type: null,
  //           value: 370,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Additional Rate',
  //           name: 'ADDITIONAL_RATE',
  //           // type: null,
  //           value: 140,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range',
  //           name: 'DATE_RANGE',
  //           // type: null,
  //           value: 'Early Bird',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range Date',
  //           name: 'DATE_RANGE_DATE',
  //           // type: null,
  //           value: '03/25/2022',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         }
  //       ],
  //       hidden: null,
  //     },
  //     {
  //       label: 'Wireless Printer For Tablet',
  //       name: 'wireless_printer_for_tablet',
  //       fieldsList: [
  //         {
  //           label: 'ON/Off Package',
  //           name: 'ON_OFF_PACKAGE',
  //           // type: null,
  //           value: true,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Image URL',
  //           name: 'IMAGE_URL',
  //           // type: null,
  //           value:
  //             'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/f0cfd19f-aa24-45f5-b971-7f1985023615_icon1.PNG',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Learn More',
  //           name: 'LEARN_MORE',
  //           // type: null,
  //           value: 'https://xyz',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Max Quantity',
  //           name: 'MAX_QUANTITY',
  //           // type: null,
  //           value: 100,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Includes Description',
  //           name: 'DESCRIPTION',
  //           type: 'p',
  //           value: 'App activations, 15 pieces of literature (PDFs up to 5 MB each) and 5 links to videos.',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Base Price/Rate',
  //           name: 'RATE',
  //           // type: null,
  //           value: 370,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Additional Rate',
  //           name: 'ADDITIONAL_RATE',
  //           // type: null,
  //           value: 140,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range',
  //           name: 'DATE_RANGE',
  //           // type: null,
  //           value: 'Early Bird',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range Date',
  //           name: 'DATE_RANGE_DATE',
  //           // type: null,
  //           value: '03/25/2022',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         }
  //       ],
  //       hidden: null,
  //     },
  //     {
  //       label: 'Wireless Printer For App',
  //       name: 'wireless_printer_for_app',
  //       fieldsList: [
  //         {
  //           label: 'ON/Off Package',
  //           name: 'ON_OFF_PACKAGE',
  //           // type: null,
  //           value: true,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Image URL',
  //           name: 'IMAGE_URL',
  //           // type: null,
  //           value:
  //             'https://csi-event-images.s3.us-east-2.amazonaws.com/Qualifications/f0cfd19f-aa24-45f5-b971-7f1985023615_icon1.PNG',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Learn More',
  //           name: 'LEARN_MORE',
  //           // type: null,
  //           value: 'https://xyz',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Max Quantity',
  //           name: 'MAX_QUANTITY',
  //           // type: null,
  //           value: 100,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Includes Description',
  //           name: 'DESCRIPTION',
  //           type: 'p',
  //           value: 'App activations, 15 pieces of literature (PDFs up to 5 MB each) and 5 links to videos.',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Base Price/Rate',
  //           name: 'RATE',
  //           // type: null,
  //           value: 370,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Additional Rate',
  //           name: 'ADDITIONAL_RATE',
  //           // type: null,
  //           value: 140,
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range',
  //           name: 'DATE_RANGE',
  //           // type: null,
  //           value: 'Early Bird',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         },
  //         {
  //           label: 'Date Range Date',
  //           name: 'DATE_RANGE_DATE',
  //           // type: null,
  //           value: '03/25/2022',
  //           disable: false,
  //           required: true,
  //           visible: true,
  //           isActive: true,
  //         }
  //       ],
  //       hidden: null,
  //     }
  //   ]
  // }
];

export const WorkflowList: WorkflowData[] = [
  {
    workflow: 'attendee',
    pageList: attendeePageList,
  },
  {
    workflow: 'exBooth',
    pageList: exBoothPageList,
  },
  {
    workflow: 'show organizer',
    pageList: showOrganizerPageList,
  },
  {
    workflow: 'exhibitor service group (ESG)',
    pageList: ESGPageList,
  },
];

export const mandatoryFields = [
  {
    workflow: 'attendee',
    value: attendeeMandatoryFields,
  },
  {
    workflow: 'exBooth',
    value: exBoothMandatoryFields,
  },
  {
    workflow: 'show organizer',
    value: [],
  },
  {
    workflow: 'exhibitor service group (ESG)',
    value: ESGMandatoryFields,
  },
];
